version: '0.2'
language: en
ignorePaths:
  - node_modules
  - .git
  - .svelte-kit
  - build
  - dist
  - coverage
  - package-lock.json
  - package.json
  - pnpm-lock.yaml
  - src/lib/paraglide
  - src/lib/server/db/auth.schema.ts
  - src/stories/assets
files:
  - '**/*.{ts,js,svelte,json,md,yaml,yml}'
words:
  - ASUS
  - authschema
  - autodocs
  - Bento
  - bigserial
  - canrun
  - commentable
  - cooldown
  - cooldowns
  - dbname
  - drizzle
  - EBML
  - Elswin
  - esbuild
  - eslint
  - FTYP
  - haha
  - hasfollowing
  - hasnavigation
  - HENG
  - inlang
  - iscloudinary
  - isexpanding
  - iskeeploading
  - isloaded
  - ismedia
  - isnavigating
  - isnext
  - isom
  - ison
  - ispost
  - isrelationship
  - issearching
  - Iwasaki
  - Kimyoo
  - Kysely
  - lfill
  - mdsvex
  - MOUYHEANG
  - msnv
  - neondatabase
  - NGOV
  - nosniff
  - OneDrive
  - opsz
  - paraglide
  - PHEARITH
  - PICH
  - playwright
  - plpgsql
  - pooler
  - prettierrc
  - quicktime
  - Rachna
  - remoteip
  - SENG
  - sonarjs
  - sslmode
  - storybook
  - sveltekit
  - SvelteKit
  - Sinya
  - tailwindcss
  - timestamptz
  - tsquery
  - tsvector
  - upserted
  - vitest
  - wght
  - nonselectable
