version: '0.2'
language: en
ignorePaths:
  - node_modules
  - .git
  - .svelte-kit
  - build
  - dist
  - coverage
  - package-lock.json
  - package.json
  - pnpm-lock.yaml
  - src/lib/paraglide
  - src/lib/server/db/auth.schema.ts
  - src/stories/assets
files:
  - '**/*.{ts,js,svelte,json,md,yaml,yml}'
words:
  - ASUS
  - authschema
  - autodocs
  - Bento
  - dbname
  - drizzle
  - esbuild
  - eslint
  - haha
  - inlang
  - Kysely
  - mdsvex
  - neondatabase
  - OneDrive
  - paraglide
  - playwright
  - pooler
  - prettierrc
  - sonarjs
  - sslmode
  - storybook
  - sveltekit
  - SvelteKit
  - tailwindcss
  - vitest
